### ISSUE TITLE
Switch to vendor JWT authentication middleware

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#102]

**Comment by kberzinch** [comment]
@ryanstrat how much do you care about getting 401 back for no token?

The 400 you mentioned at one point in Slack is currently being output by our middleware, which works identically to the vendor middleware. If that is acceptable, we will switch to the vendor middleware.

If you feel strongly about it, I'll close this issue and update our middleware to return a 401 if no token present.

**Comment by kberzinch** [comment]
Move to vendored middleware per 10/10 meeting.

**Comment by RossIV** [comment]
Correction-  We're _not_ moving to the vendor middleware. Closing issue.
