### ISSUE TITLE
Illuminate\Database\QueryException in POST /nova-api/teams/6/attach/users

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#1046]
## Error in Apiary

**Illuminate\Database\QueryException** in **POST /nova-api/teams/6/attach/users**
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `team_user` (`team_id`, `user_id`, `created_at`, `updated_at`) values (6, ?, 2020-01-09 19:35:59, 2020-01-09 19:35:59))

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5e1239914fba15001946bce6?event_id=5e17c6ef0055b8c01b2c0000&i=gh&m=ci)

## Stacktrace

    Http/Middleware/CASAuthenticate.php:134 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5e1239914fba15001946bce6?event_id=5e17c6ef0055b8c01b2c0000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
This is apparently not actually fixable, we can add `required(true)` to the field but it only adds an asterisk to the field label when attaching.
