### ISSUE TITLE
PUT /api/v1/users/:user throws an exception when no Google account is linked

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#1077]
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **PUT /api/v1/users/928**
strtolower() expects parameter 1 to be string, null given

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5e2de57c7d5177001ab24c37?event_id=5e2de5840055fda53ea80000&i=gh&m=ci)

## Stacktrace

    Http/Controllers/UserController.php:175 - strtolower
    Http/Controllers/UserController.php:175 - App\Http\Controllers\UserController::update
    Http/Middleware/PermissionMiddleware.php:34 - App\Http\Middleware\PermissionMiddleware::handle
    Http/Middleware/CASAuthenticate.php:134 - App\Http\Middleware\CASAuthenticate::handle
    Http/Middleware/APITokenAuthenticate.php:38 - App\Http\Middleware\APITokenAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5e2de57c7d5177001ab24c37?event_id=5e2de5840055fda53ea80000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by JoshOldenburg** [comment]
https://github.com/RoboJackets/apiary/blob/master/app/Http/Controllers/UserController.php#L175
