### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError in GET /nova-api/users

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#1148]
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /nova-api/users**
Return value of App\Nova\Filters\UserActive::apply() must be an instance of Illuminate\Database\Eloquent\Builder, instance of Illuminate\Database\Eloquent\Relations\BelongsToMany returned

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5e762f7be71b650017934248?event_id=5e762f7b0058dd50ca370000&i=gh&m=ci)

## Stacktrace

    Nova/Filters/UserActive.php:28 - App\Nova\Filters\UserActive::apply
    Http/Middleware/CASAuthenticate.php:143 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5e762f7be71b650017934248?event_id=5e762f7b0058dd50ca370000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
Occurred when filtering users on major view
