### ISSUE TITLE
Hamburger not opening tabs

### ISSUE THREAD

**Issue by thayes46** [RoboJackets/apiary#1226]
Whenever the window of the dashboard page is not large enough to display all tabs and condenses to a hamburger, clicking on the hamburger doesn't reveal a menu to select a tab. The only workaround is to full screen the window, select the tab, then resize or snap.

**Comment by kberzinch** [comment]
This also appears to impact the mobile web interface

**Comment by kberzinch** [comment]
Seems to be fixed in prod now.
