### ISSUE TITLE
Make a User Look-up component

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#123]
Throughout the app, there are many places where we need a form field that holds the value of a user ID or UID. However, our users want to be able to find users by typing their name.

Users should be able to type a name, gtid, or uid into the box and receive a typeahead-like list of matching Users. The vue component will emit the either uid or the id of the user, based on a config set by a prop. The default should be to emit a uid.

**Comment by ryanstrat** [comment]
https://github.com/matiastucci/vue-input-tag

**Comment by RossIV** [comment]
I have this mostly implemented with http://sagalbot.github.io/vue-select/, just trying to figure out a bug I'm running into with debouncing.

**Comment by RossIV** [comment]
This is mostly complete. It emits the selected user object, rather than just one attribute which IMO is more flexible. Only thing left is to tweak the filter logic to display names when searching with a GTID or username. OOTB it doesn't do that.
