### ISSUE TITLE
Payments per Day and Attendance per Week do not update with time scale

### ISSUE THREAD

**Issue by thayes46** [RoboJackets/apiary#1261]
On the admin dashboard, using the dropdown to select a time period updates the graph display but the number persists for the day or week, respectively.

**Comment by kberzinch** [comment]
I think this is a limitation with Nova

**Comment by JoshOldenburg** [comment]
The number is the most recent day/week’s data, by design in Nova.

**Comment by kberzinch** [comment]
gottem
