### ISSUE TITLE
Require corp liability waiver during dues flow

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#1265]
Lots of grooming to do on this but I think we should talk about it.

**Comment by JoshOldenburg** [comment]
Per Slack discussion with @ryanstrat and @kberzinch, we're going to implement this with Docusign, at least for the spring 2020 semester.

**Comment by kberzinch** [comment]
Schema changes:

```diff
> membership_agreement_template
> --
> id int(10) PK IDENTITY
> revision_date timestamp
> text varchar(255)
> 
> executed_agreement
> --
> id int(10) PK IDENTITY
> template_id int(10) FK >- membership_agreement_template.id
> user_id int(10) FK >- users.id
> agreement_timestamp timestamp
> ip_address varchar(255)
> cas_ticket varchar(255)
> user_agent varchar(255)
> service_url varchar(255)

```

**Comment by kberzinch** [comment]
Also drop column `accept_safety_agreement` from users table

**Comment by JoshOldenburg** [comment]
The SCC safety agreement will be part of the membership agreement.

**Comment by kberzinch** [comment]
Possibly grab location/AS information from https://ipstack.com/?
