### ISSUE TITLE
Can't create service accounts from Nova easily

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#1277]
## Error in Apiary

**Illuminate\Database\QueryException** in **POST /nova-api/users**
SQLSTATE[HY000]: General error: 1364 Field 'has_ever_logged_in' doesn't have a default value (SQL: insert into `users` (`uid`, `preferred_name`, `first_name`, `last_name`, `gt_email`, `personal_email`, `gtid`, `phone`, `github_username`, `github_invite_pending`, `gmail_address`, `clickup_email`, `clickup_invite_pending`, `exists_in_sums`, `emergency_contact_name`, `emergency_contact_phone`, `shirt_size`, `polo_size`, `is_service_account`, `create_reason`, `gtdirguid`, `updated_at`, `created_at`) values (svc_reservations, ?, Service Account, for Reservations, robojackets-it@lists.gatech.edu, ?, 999999993, ?, ?, 0, ?, ?, 0, 0, ?, ?, ?, ?, 1, manual, ?, 2020-07-27 20:54:11, 2020-07-27 20:54:11))

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5f1f7733481e41001843ee30?event_id=5f1f7733005b6d09c2a50000&i=gh&m=ci)

## Stacktrace

    app/Http/Middleware/CASAuthenticate.php:143 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5f1f7733481e41001843ee30?event_id=5f1f7733005b6d09c2a50000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by JoshOldenburg** [comment]
In addition to that error, our standard is to use a non-GT email in the gt_email field, which you can't do from Nova.

**Comment by kberzinch** [comment]
Fixed the boolean issue in daa17a8f29a7d62322d271767e31d44758985eb8

**Comment by kberzinch** [comment]
robojackets.org emails seem to work in the GT email field now so I'm going to close this
