### ISSUE TITLE
Secondary Vapor migration changes

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#1310]
- [ ] Must run dues package expiration job when dues packages expire (formerly done by `DuesPackageObserver` but SQS is limited on delay length)
- [ ] Must run `PushToJedi` when access overrides expire (same issue as above but with `UserObserver`)
- [ ] Bugsnag version needs to come from an environment variable
- [x] Needs a real domain name (pending Vapor support)
- [ ] Fix resume uploads and re-enable them

**Comment by kberzinch** [comment]
How do you want to handle the first two? Daily job?

**Comment by JoshOldenburg** [comment]
Yeah, I think that's the only option.

**Comment by kberzinch** [comment]
Closing since we're sticking with colo
