### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError in App\Notifications\GeneralInterestNotification

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#137]
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **App\Notifications\GeneralInterestNotification**
Call to a member function routeNotificationFor() on string

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/59aab748c1d5f4001828f5f2?event_id=59aab748c1d5f4001828f5f1&i=gh&m=ci)

## Stacktrace

    vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php:48 - Illuminate\Notifications\Channels\MailChannel::send

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/59aab748c1d5f4001828f5f2?event_id=59aab748c1d5f4001828f5f1&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by RossIV** [comment]
Whoops, my bad. Fixing.
