### ISSUE TITLE
Allow selecting alternate merch

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#1482]
Basically, implement this:

>This is my general plan or what I was thinking of: anyone who hasn’t gotten a polo needs one, so they shouldn’t be presented with this choice. If a member has had their polo marked as “picked up” in a previous semester, then they should be presented with a short survey. I was thinking put it maybe next to the resume block on the home screen. it should be a simple multiple choice like “Our records indicate you have already received a RoboJackets polo. Please select your preferred merchandise for this year’s spring dues: ” with an option for “Polo” and an option for the other thing (probably hoodie or whatever the PR chair decides to order that year). When they hit confirm, if they selected the other option that isn’t polo, maybe prompt them to enter their size for the merch. That’s all I was thinking. If the member doesn’t fill out the survey, it should default to polo. is this enough info?

Exact implementation details are TBD. The question should be prompted during the dues flow and the alternate(s) should be configurable.

**Comment by kberzinch** [comment]
Schema changes:
```diff
66,67d65
< eligible_for_shirt tinyint(1) DEFAULT='0'
< eligible_for_polo tinyint(1) DEFAULT='0'
76a75,81
> students_only boolean
> fiscal_year_id int(10) FK >- fiscal_years.id
> 
> fiscal_years
> --
> id int(10) PK IDENTITY
> year int(4) UNIQUE
81,84d85
< swag_shirt_provided timestamp NULL
< swag_shirt_providedBy int(10) INDEX NULL FK >- users.id
< swag_polo_provided timestamp NULL
< swag_polo_providedBy int(10) INDEX NULL FK >- users.id
89a91,126
> 
> merch
> --
> id int(10) PK IDENTITY
> name varchar(255)
> fiscal_year_id int(10) FK >- fiscal_years.id
> type varchar(255)
> 
> dues_package_merch_eligibility
> --
> dues_package_id int(10) FK >- dues_packages.id
> merch_id int(10) FK >- merch.id
> 
> dues_transaction_merch_selections
> --
> dues_transaction_id int(10) FK >- dues_transactions.id
> merch_id int(10) FK >- merch.id
> provided_timestamp timestamp NULL
> provided_by int(10) FK >- users.id
> 

```

**Comment by JoshOldenburg** [comment]
Steps for implementing this:

- [x] Migration to make `merch` model and pivot tables
- [x] Migration to move data from old swag columns to merch pivots
- [ ] Migration to drop old swag columns
- [ ] `Merch` model
- [ ] Update Nova action
- [ ] Update HTTP controllers/resources
- [ ] Update dues flow (including logic to ensure everyone has a polo)
