### ISSUE TITLE
Add "Active Member" flag to user model

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#150]
Dues will have effective start and end dates. These should be queried to determine whether a member is considered "Active".

**Comment by RossIV** [comment]
We should, theoretically, be able to accomplish this with an Eloquent local scope, but I'll have to see how to do this in a manner that isn't completely gross. Pending further investigation.

**Comment by RossIV** [comment]
Referencing notes from our last meeting, I want to make sure that the following assumption is correct for a member being 'active':

Member has made a payment for dues for a term (or in Apiary terms a `DuesPackage`). For that `DuesPackage`, the current date is between the `effective_start` and `effective_end`.

**Comment by RossIV** [comment]
@ryanstrat Approved the above statement. Code added in 79b7d50.
