### ISSUE TITLE
BuzzCard Access Export

### ISSUE THREAD

**Issue by RossIV** [RoboJackets/apiary#1563]
Due to the somewhat complicated means of granting BuzzCard access to 575 14th as part of the S2 implementation, we should add a Nova feature to generate appropriate CSVs to be sent to relevant staff.

Two CSVs will need to be generated. One with Core members which grants access to all SCC areas and the RJ Shop, and another with everyone else to be granted access to everything except the RJ shop. There should not be any duplication of GTIDs between the two files.

Related: https://github.com/RoboJackets/apiary/issues/1560

**Comment by JoshOldenburg** [comment]
I'd suggest generalizing the `AttendanceReportController` and its matching Nova action.

**Comment by kberzinch** [comment]
I would also like to restrict it to team attendance in some fashion though that's a little complicated until https://github.com/RoboJackets/people-counter/issues/7 is done
