### ISSUE TITLE
Delay dues form reminder email

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#1594]
From @barulicm - to reduce the email spam we send, we should delay the ACTION REQUIRED email for a few minutes and skip it if payment has been received in the interim

**Comment by kberzinch** [comment]
More from @barulicm

>Consider only sending the "ACTION REQUIRED" email from the dues page if the person doesn't complete the online payment process within some timeout. ie. If I immediately pay, don't send an extra email. I don't even know if this is actually possible, but it'd be nice.

**Comment by barulicm** [comment]
It's such a good idea, I had it twice! 😄

**Comment by barulicm** [comment]
Oh sweet, thanks!
