### ISSUE TITLE
TypeError in /dues

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#1601]
## Error in Apiary

**TypeError** in **/dues**
Cannot read property 'forEach' of undefined

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/60170507a9a89a0017dcf700?event_id=601705b00069a191aee20000&i=gh&m=ci)

## Stacktrace

    https://my.robojackets.org/js/app.js:2 - o.duesPackageChoice

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/60170507a9a89a0017dcf700?event_id=601705b00069a191aee20000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
Happens after selecting a dues package for a totally new user
