### ISSUE TITLE
Force clear cache on assets

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#1649]
There's a recurring issue with the CSS cache being out of date on Chrome.

**Comment by kberzinch** [comment]
This really shouldn't be possible; there is a randomized value added to the query string for resources that changes on every deploy.

I accept that it _is_ happening, I'm just completely stumped as to why.

**Comment by kberzinch** [comment]
I think this should be fine now. We are no longer setting any cache headers other than `ETag` so browsers should be checking with the server on every page load.
