### ISSUE TITLE
SQL error on first run: SQLSTATE[HY000]: General error: 1364 Field 'rank_order' doesn't have a default value

### ISSUE THREAD

**Issue by evan10s** [RoboJackets/apiary#1757]
It looks like the `class_standings` table doesn't have a seeder, so when you sign in for the first time on a fresh install, your class standing entry has to be created, which doesn't work because no value is specified for the `rank_order` column on that table.  If you manually add the row it's trying to create to the `class_standings` table then everything works fine and dandy.

```
SQLSTATE[HY000]: General error: 1364 Field 'rank_order' doesn't have a default value (SQL: insert into `class_standings` (`name`, `updated_at`, `created_at`) values (masters, 2021-05-22 22:19:52, 2021-05-22 22:19:52))
```

**Comment by kberzinch** [comment]
Huh, i did not think of that. I think the correct behavior would be to pick the lowest available value.

The rank order field is intended to be used for nova UX but we did not know all of the values in advance when we added that.

**Comment by kberzinch** [comment]
Or i guess just default to null
