### ISSUE TITLE
Set up CI service to Generate API docs and publish to Github Pages

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#18]

**Comment by kberzinch** [comment]
Are you aiming to write something inline with PHP or as a separate document? There are a few options for each.

**Comment by ryanstrat** [comment]
Inline comments.

**Comment by kberzinch** [comment]
[apidocjs.com](http://apidocjs.com/) looks reasonable. What do you think?

**Comment by kberzinch** [comment]
Would you rather have the site hosted off a `gh-pages` branch or a `docs` folder?

**Comment by kberzinch** [comment]
Finished across various PRs and commits today.
