### ISSUE TITLE
IAA export for trips

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#181]
The following information for each student is required to process IAAs:

- Student Name (loaded from CAS - do we need to request a legal name attribute?)
- GTID (loaded from CAS)
- ~GT Email (loaded from CAS)~
- Emergency Contact Name (should be collected at dues payment time)
- ~Emergency Contact Relationship (not currently collected)~
- Emergency Contact Phone # (should be collected at dues payment time)

List courtesy of Dr. C.

**Comment by ryanstrat** [comment]
I feel like this answers the question raised in #316 

We still sometimes need DoB and passport info for booking international travel or competition registration.

**Comment by kberzinch** [comment]
DOB should be retained for a limited time period only, 90 days suggested.
