### ISSUE TITLE
Add route to support verified Android App Links

### ISSUE THREAD

**Issue by evan10s** [RoboJackets/apiary#1813]
See https://developer.android.com/training/app-links/verify-site-associations

**Comment by kberzinch** [comment]
It looks like this would grab all links under https://my.robojackets.org. Is there a good way to kick back to a browser if the mobile app does not have a screen for a given web URL (which will be very common for a very long time?)

**Comment by evan10s** [comment]
That's definitely possible, but you can also limit to specific paths in the manifest element.  I ended up handling the deep link with a custom URL scheme (e.g., `org.robojackets.apiary://blah`), which has better compatibility and does what we need for now.

**Comment by evan10s** [comment]
Closing, no longer needed
