### ISSUE TITLE
Dues production deployment punchlist

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#184]
- [x] Update SCC rules
- [x] Navbar permissions
- [x] Hide the join and graduation dates in profiles
- [x] ~~Soft deletes on all models~~
- [x] Verify database backups are encrypted
- [x] Encrypt production users table
- [x] Populate dues packages in production

**Comment by ryanstrat** [comment]
I did my 3 things. @kberzinch all you now

**Comment by kberzinch** [comment]
Moving soft deletes to new issue
