### ISSUE TITLE
Resume book export should filter out alumni

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#1849]
It checks that the `primary_affiliation` is `student`, but it should look for non-student dues packages like the buzzcard export.

**Comment by kberzinch** [comment]
I think it already does that

https://github.com/RoboJackets/apiary/blob/f122b5e6c69dd4c00f6d90b3c55d340421e9972a/app/Nova/Actions/ExportResumes.php#L69-L70
