### ISSUE TITLE
Illuminate\Database\QueryException in GET /nova-api/dues-packages

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#1863]
## Error in Apiary

**Illuminate\Database\QueryException** in **GET /nova-api/dues-packages**
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_active' in 'order clause' (SQL: select * from `dues_packages` where `dues_packages`.`deleted_at` is null order by `is_active` asc limit 26 offset 0)

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/60fb1ad11089c50007635b06?event_id=60fb1ad1007fa4ab23980000&i=gh&m=ci)

## Stacktrace

    app/Http/Middleware/CASAuthenticate.php:100 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/60fb1ad11089c50007635b06?event_id=60fb1ad1007fa4ab23980000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
active column should not be sortable
