### ISSUE TITLE
UIDs for Square Cash payments

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#188]
Ask for UIDs in the Square Cash payment instructions. Display them in the pending dues table.

**Comment by ryanstrat** [comment]
@kberzinch What would you like the new copy for the card to be?

The current copy is 
`Pay with your debit card online via SquareCash to $robojackets.`

**Comment by kberzinch** [comment]
Add
>Please put your GT username (e.g. gburdell3) in the notes.
