### ISSUE TITLE
Design General Interest Announcement Email

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#19]

**Comment by kberzinch** [comment]
Bonus points if you can set up an [RSVP action](https://developers.google.com/gmail/markup/reference/rsvp-action).

**Comment by kberzinch** [comment]
I worked on RSVP actions some today and could not for the life of me get one to show up.

You're supposed to be able to email yourself to test, but I couldn't get it working.

**Comment by kberzinch** [comment]
Also I assume you have a template from last year? If you could post it here and/or send it to me I can work on making it a `Mailable`.
