### ISSUE TITLE
Add a Logout Button

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#193]
Issue courtesy of @2Ryan09 

@RossIV What is the logout URL?

**Comment by kberzinch** [comment]
https://login.gatech.edu/cas/logout?service=https://app-url-here.tld/

Fun fact: that page works even if you're not logged in.

If you leave off the service parameter it'll force a CAS logout.

**Comment by kberzinch** [comment]
I'm not sure if there's a route for Laravel logoff yet
