### ISSUE TITLE
Add offline support for the kiosk

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#1957]
Some temporary local storage (just in RAM to avoid data protection concerns?) would allow us to act like the monthly maintenance downtime doesn't happen. Cache failed requests and push them all up when they start succeeding again.

**Comment by kberzinch** [comment]
This has proven to be tricky in the past (recruiting).

**Comment by kberzinch** [comment]
Server reliability has improved significantly since this issue was opened, and I don't think this is worth the added complexity.
