### ISSUE TITLE
Automatically un-sticky the team on the kiosk

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#1988]
Wait for some amount of time (an hour?) with no taps.

**Comment by evan10s** [comment]
@RossIV and I discussed adding a 1-2 minute SweetAlert timer to the dialog after which it will auto-close

**Comment by JoshOldenburg** [comment]
Per Slack discussion, close the modal after 1-2min if not sticky and no card is presented. If sticky, close after 10-15min of no cards being presented.
