### ISSUE TITLE
API Endpoints for FASET

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#2]
Complete API endpoints for submitting the FASET form response

The API endpoint may be unauthenticated or protected by CAS
The API endpoint shall receive the following attributes:

- faset_name
- faset_email
- array of survey question responses

**Comment by kberzinch** [comment]
Any reason you'd want it unauthenticated?

**Comment by ryanstrat** [comment]
Only so that completing CAS integration is not a dependency for the FASET 1 release

**Comment by kberzinch** [comment]
Ah. #4 shouldn't be _that_ long but I'll prioritize #3.
