### ISSUE TITLE
Implement admin masquerade-on-demand option for debugging

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#2073]
Allowing admins to act like another user (like Canvas) could speed up debugging significantly. Enter the mode with a Nova action on a user. There should be a banner (or similar) to make it obvious when you're in that mode. This needs some thought to avoid introducing weird/inconsistent data to the DB.

https://github.com/404labfr/laravel-impersonate

**Comment by kberzinch** [comment]
What are you concerned about wrt the database?
