### ISSUE TITLE
Send General Interest Invites

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#22]
Allow Officer I role to send GI Interest Invites.

Invites should be sent via mailgun (via laravel mail) and should be batched at a rate of not more than 50 per hour, to comply with GT inbound rate limiting.

**Comment by kberzinch** [comment]
How did you handle the rate limiting last year? I thought Mailgun handled most of that.

**Comment by kberzinch** [comment]
Thoughts on architecting this?
