### ISSUE TITLE
Preferred Name copy

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#226]
Change input label to "Preferred First Name". Pre-fill with legal first name.

These changes should clarify the purpose of the field.

**Comment by ryanstrat** [comment]
This is kinda non-trivial from a model perspective. You have to keep track of whether the form field is dirty to actually decide whether to commit it to the db or not.

**Comment by kberzinch** [comment]
Are there any drawbacks to just always writing to DB?

**Comment by ryanstrat** [comment]
If GT ever changes it, preferred name wouldn't also change.

**Comment by kberzinch** [comment]
Good point...

How about checking to see if it matches legal name in the controller, and not storing if so?

**Comment by ryanstrat** [comment]
Yeah, that's basically how I would implement it

**Comment by ryanstrat** [comment]
Vuelidate has a "sameAs" validator we could use to error out the field if it matches the user's given name. This change would require additional server-side validation, but that would handle the UI aspect of that.
