### ISSUE TITLE
User-facing dues status

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#228]
- List of dues payments made
 - Current dues status (active/not)
 - Active until X date (from dues package)

**Comment by kberzinch** [comment]
>It would be nice to have a small notification text/symbol/something to show that you have already paid dues (or rather, submitted a dues request). Something under or near the pay dues box that shows what semesters you have indicated paying dues for.

**Comment by JoshOldenburg** [comment]
The current status and active until date both appear on the dashboard currently. A list of past payments is still necessary.
