### ISSUE TITLE
Set up Mailgun Integration

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#23]
Configure Laravel Mail to use Mailgun as the backing service

**Comment by kberzinch** [comment]
RoboJackets Admin and I now both have accounts. I put my credit card on there with a hard limit of 1k emails to prevent me from actually being charged.

I'll set up `my.robojackets.org` as the domain with tracking links generated at `mail.my.robojackets.org`.

The Laravel side of things will get set up once the domain is verified and I've confirmed that messages are passing DKIM and SPF.

**Comment by ryanstrat** [comment]
We should set that up using an official card. I don't anticipate sending more than 1k per month anyway.

**Comment by kberzinch** [comment]
This is pending migration to HE.net since Namecheap seems to have completely stopped working and I don't feel like performing the requisite rituals to make it behave this week.

**Comment by kberzinch** [comment]
Mailgun domain is set up and verified.

Remaining work:
- [ ] Reconfigure tracking domain to be routed through server
- [ ] Set up Laravel side

- [ ]
