### ISSUE TITLE
User Onboarding via GI Invite

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#24]
When a person clicks the tracked link in the GI invitation email, we will passively see if they are logged into GT login. If they are logged in, a user object will be created and linked to the FASET visit.

If the user is not logged in, the RSVP will be recorded, but without a user specified.

**Comment by kberzinch** [comment]
You don't just want to force authentication?

**Comment by ryanstrat** [comment]
I'm concerned that it will reduce response rate

**Comment by kberzinch** [comment]
Also so I don't forget: the FASET submission endpoint could bootstrap a basic user object from Whitepages. Idk if that's something we want it to do, but it is technically possible

**Comment by ryanstrat** [comment]
Per discussion on Slack, it was decided that this is not something we would want to do.

**Comment by ryanstrat** [comment]
This is done!
