### ISSUE TITLE
Enter transaction fees as a "tax"

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#240]
Calculate the appropriate percentage amount to add a $3 surcharge to the transaction, then add it as a tax with label "Card Processing Fee".

This is slightly dumb, yes.

**Comment by JoshOldenburg** [comment]
This would make it more clear that the fee doesn't go to us.

**Comment by kberzinch** [comment]
Looks like this was implemented in ba4d4280253b09311533416dace8a827a14bb3d8 but that branch has been dead for eternity.
