### ISSUE TITLE
Role membership audit report

### ISSUE THREAD

**Issue by evan10s** [RoboJackets/apiary#2563]
Nova only lets you view the users who have a given role in increments of 5 users at a time, which is really inconvenient for revoking roles from people who are no longer in leadership positions after elections in the spring.

This would be a way to view all people who have a given role and maybe details like when the role was attached, etc., so we can determine quickly if they still need access.

**Comment by kberzinch** [comment]
This might be better suited for Metabase

**Comment by evan10s** [comment]
Completed in Metabase: https://metabase.bcdc.robojackets.net/dashboard/3-role-audit
