### ISSUE TITLE
Global search is acting up

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#2589]
Searching on the user page gives different (better) results than the user section of the global search, for the same input. Seems like Nova's fault maybe?

**Comment by JoshOldenburg** [comment]
The last name of https://my.robojackets.org/nova/resources/users/1749 for instance has no other exact matches, but they don't show up in the top five users in global search. They're the first result when searching on user index.

**Comment by kberzinch** [comment]
another bad search - `ishan`

**Comment by JoshOldenburg** [comment]
Also full name of https://my.robojackets.org/nova/resources/users/4049
