### ISSUE TITLE
Rename travel to trips

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#2618]
Frontend change only. Some places will still make more sense with the word "travel", such as the menu bar.

**Comment by kberzinch** [comment]
"Travel forms" on travel page -> "trip forms"

**Comment by kberzinch** [comment]
"Travel fee" -> "trip fee" (only shown in Square?)

**Comment by kberzinch** [comment]
"Travel" model in Nova -> "Trip" model

"Travel Assignment" model in Nova -> "Trip Assignment" model
