### ISSUE TITLE
Show a card to invite members to Engage after paying dues

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#268]
Related to, but distinct from, #245

**Comment by ryanstrat** [comment]
Check for CAS attributes. Could be a new DB column.

**Comment by JoshOldenburg** [comment]
There's no longer a CAS attribute for membership after the switch to Engage.

**Comment by kberzinch** [comment]
Do we have any other way of checking membership?

If not, one thing that's kind of dumb but I've seen elsewhere is just checking to see if the link was visited, i.e. have it go to an apiary endpoint first that flags the user as having visited it.

**Comment by evan10s** [comment]
No longer necessary per Alex
