### ISSUE TITLE
Improve display of detailed self-service access override eligibility status

### ISSUE THREAD

**Issue by evan10s** [RoboJackets/apiary#2814]
Use Nova [BooleanGroupField](https://nova.laravel.com/docs/4.0/resources/fields.html#boolean-group-field) similar to what we do for travel:

![image](https://user-images.githubusercontent.com/5790137/187340152-6bd24c10-63ae-4135-9383-45e8ddbdef38.png)

**Comment by kberzinch** [comment]
Implemented as part of #3720
