### ISSUE TITLE
FASET Survey Form

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#3]
Frontend for FASET

Static form to ask needed questions for member onboarding.

The form must:

- Collect and validate a user's name (and submit as faset_name)
- Collect and validate a user's email (and submit as faset_email)
- Static representations of the 2 survey questions ( and submit as an array of responses [Schema TBD])

**Comment by kberzinch** [comment]
Where are we pulling question info?

**Comment by ryanstrat** [comment]
Hard code it for now.

I've done a fair amount of thinking on this as well and would like further verbal discussion.

**Comment by ryanstrat** [comment]
This is being converted to bootstrap

**Comment by ryanstrat** [comment]
This has been completed
