### ISSUE TITLE
Replace Glyphicons

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#35]
Bootstrap 4 removed the included set of Glyphicons.

Replace with [Material Icons](http://google.github.io/material-design-icons/)

Import as an Icon Font

**Comment by ryanstrat** [comment]
https://justineo.github.io/vue-awesome/demo/

**Comment by ryanstrat** [comment]
Alternatively considering this icon-set which is compatible with the Form Wizard: https://themify.me/themify-icons

**Comment by kberzinch** [comment]
Check to see if icons are currently being used anywhere in the app. Close if not.

**Comment by Arthelon** [comment]
Did a search of the views/assets folders and double-checked most of the pages manually. I don't think there are any bootstrap glyphicons being used right now.

**Comment by kberzinch** [comment]
I'm going to close this issue as currently there are no icons to replace.

If at some point we want to use icons, we'll find a solution then.
