### ISSUE TITLE
Condense Dues/Accept Dues, Swag/Give Swag Pages

### ISSUE THREAD

**Issue by RossIV** [RoboJackets/apiary#352]
There are presently four distinct pages for Dues and Swag Ops - Dues, Accept Dues, Swag, Give Swag. This is kinda dumb since all four are just tables with different data. These pages should be collapsed into two - one "Dues" and one "Swag" - with toggle buttons to change the data in the table appropriately and the extraneous menu options removed.

**Dues**
Initial page load should match the as-is page. Add a button to filter the data table entries down to just those who have not paid.

**Swag**
Initial page load should match the as-is page. Add a button to filter the data table entries down to just those who have outstanding swag (needs to be picked up).

**Comment by kberzinch** [comment]
For the record, I object to this being in the May milestone.

**Comment by RossIV** [comment]
Then change it
