### ISSUE TITLE
Implement CAS Login

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#4]
Implement CAS authentication as middleware

**Comment by kberzinch** [comment]
Basic authentication was added in #10, but I don't think this really counts as closed until we're actually logging in users per se.

**Comment by kberzinch** [comment]
Additional work is incorporated as part of #91.

**Comment by ryanstrat** [comment]
@kberzinch Are we ready to call this done?

**Comment by ryanstrat** [comment]
Still need to reload attributes on each login

**Comment by RossIV** [comment]
Fixed in #179
