### ISSUE TITLE
Clarify that travel fields are per-person not total

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#4019]
Can we also add some validation to the trip fee field to check the math?

**Comment by sukuasoft** [comment]
@kberzinch 
Can I work on this issue?

**Comment by kberzinch** [comment]
Hi there! If you have experience with [Laravel](https://laravel.com/) and your own [Laravel Nova](https://nova.laravel.com/) license, then yes, you're welcome to pick it up.

While this repository itself is open-source, we use a commercial software package called Laravel Nova, and we are not able to redistribute it or share our license with you.
