### ISSUE TITLE
Selectable columns in users table

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#407]
idk how this would be implemented but it came in Make a Wish
>it'd be awesome to be able to select the email address in the users table without going to their detail page

**Comment by JoshOldenburg** [comment]
How do you feel about making just the name clickable and the rest not? The teams admin page has the Name column as a link (though the rest of the row is clickable anyway).

**Comment by kberzinch** [comment]
Fixed in Nova
