### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError in POST /api/v1/faset

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#416]
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **POST /api/v1/faset**
Type error: Argument 2 passed to Bugsnag\PsrLogger\AbstractLogger::debug() must be of the type array, string given, called in /var/www/apiary/staging/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 221

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5b860cdf08aa48001933a4de?event_id=5b860cdf002de99447680000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/FasetVisitController.php:42 - App\Http\Controllers\FasetVisitController::store
    app/Http/Middleware/PermissionMiddleware.php:32 - App\Http\Middleware\PermissionMiddleware::handle
    app/Http/Middleware/CASAuthenticate.php:61 - App\Http\Middleware\CASAuthenticate::handle
    app/Http/Middleware/APITokenAuthenticate.php:34 - App\Http\Middleware\APITokenAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5b860cdf08aa48001933a4de?event_id=5b860cdf002de99447680000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by JoshOldenburg** [comment]
This didn't happen all summer (2019), and the FasetVisitController has gone through some pretty significant changes, so this likely got fixed at some point.
