### ISSUE TITLE
Implement attendance collection for team meetings

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#44]
A kiosk-type page needs to be created to accept BuzzCard swipes for team meetings. Users should be able to select their team in a touch-friendly UI before swiping.

This issue does not include attendance collection for events, such as General Interest.

Magswipe readers will be configured to enter the 9-digit GTID number then press Enter.

**Comment by RossIV** [comment]
#287 could be useful for this, depending on how the front-end for teams goes.
