### ISSUE TITLE
ErrorException in GET /

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#440]
## Error in Apiary

**ErrorException** in **GET /**
Trying to get property 'package' of non-object

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5b9aed42e8d96e0019a57904?event_id=5b9aed61002ed8861e9b0000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/DashboardController.php:37 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    app/Http/Controllers/DashboardController.php:37 - App\Http\Controllers\DashboardController::index
    app/Http/Middleware/CASAuthenticate.php:63 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5b9aed42e8d96e0019a57904?event_id=5b9aed61002ed8861e9b0000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **GET /**](https://app.bugsnag.com/robojackets/apiary/errors/5b9aed42e8d96e0019a57904?event_id=5b9b3aeb002ebeb7d4080000&i=gh&m=eu)

**Comment by kberzinch** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **GET /**](https://app.bugsnag.com/robojackets/apiary/errors/5b9aed42e8d96e0019a57904?event_id=5b9c683b002eb9af36b20000&i=gh&m=eu)

**Comment by JoshOldenburg** [comment]
Did this get fixed? I can open https://apiary-test.robojackets.org/ again.

**Comment by kberzinch** [comment]
Not intentionally. I don't think anyone has looked at the stack trace in detail yet. We'll leave it open for now.

**Comment by kberzinch** [comment]
I did make a package active which may be related.

**Comment by JoshOldenburg** [comment]
See #452

**Comment by georgeburdell** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ErrorException** in **GET /**](https://app.bugsnag.com/robojackets/apiary/errors/5b9aed42e8d96e0019a57904?event_id=5b9d736a002ec546e6380000&i=gh&m=fx)
