### ISSUE TITLE
Accept names in the manual attendance add form

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#445]
Accept names in addition to GTIDs when adding attendance manually in [this form](https://my.robojackets.org/admin/attendance)

**Comment by kberzinch** [comment]
That's difficult because we don't really have any way to validate names or link them to GT persons.

**Comment by JoshOldenburg** [comment]
I was thinking just a search of the users database. When I've added stuff manually I have the user list on one tab and the attendance in the other and copy GTIDs between them.

**Comment by JoshOldenburg** [comment]
This is no longer relevant since we don't deal with paper attendance anymore.

**Comment by kberzinch** [comment]
How is training attendance going to be collected?

**Comment by JoshOldenburg** [comment]
It will be collected with magstripe or contactless readers.

**Comment by kberzinch** [comment]
That seems optimistic but k.
