### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError in GET /payments/complete

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#449]
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /payments/complete**
Call to undefined method SquareConnect\ApiException::getTransaction()

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5b95923f8ed4870019c5951b?event_id=5b9eb6d7002ec81d85010001&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/PaymentController.php:433 - App\Http\Controllers\PaymentController::handleSquareResponse
    app/Http/Middleware/CASAuthenticate.php:63 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5b95923f8ed4870019c5951b?event_id=5b9eb6d7002ec81d85010001&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
Log noise on OK transaction

**Comment by kberzinch** [comment]
My previous comment is incorrect - this transaction was not stored correctly. Review stack trace for details.

**Comment by JoshOldenburg** [comment]
This was caused by the issue from #448, returning an exception instead of throwing it, causing an exception here, so that issue is also likely not log noise.

**Comment by kberzinch** [comment]
Yeah we should probably rethink parts of this flow.

**Comment by kberzinch** [comment]
This is mitigated but still shouldn't be possible to begin with.
