### ISSUE TITLE
Implement basic event management

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#45]
Users should be able to CRUD events. Events can optionally have RSVP (and invite) and/or attendance tracking functionality.

**Comment by ryanstrat** [comment]
A RESTful API for this now exists, but a management GUI is needed.

**Comment by ryanstrat** [comment]
Still needs an "add event" form. Which is probably as simple as refactoring the edit form into a component.

**Comment by RossIV** [comment]
Create Event added in #285, delete button added in 221ae7f.

**Comment by RossIV** [comment]
What is left to do here?

**Comment by ryanstrat** [comment]
I think this is done.
