### ISSUE TITLE
Interacting with RoboJackets SSO applications

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#48]
We've established that working with the OrgSync API is less than ideal for a variety of reasons; however, our other hosted applications are currently using GRS roles to manage their internal user information.

100% of our authentication middleware is developed internally around the phpCAS library, which simply returns RoboJackets OrgSync group membership as an array (after a nonzero amount of SAML attribute parsing). We could conceivably replace this process with an API call to Apiary, which would enable us to manage user authorizations in real time and without involving OrgSync. Such a call would be made immediately after CAS information is available to the middleware and before the user is logged into the application.

This would be an alternative to performing group updates in OrgSync when a user moves teams in Apiary. If we were to go this route, we'd still need to keep the OrgSync functionality as a fallback for legacy users that haven't onboarded to Apiary for whatever reason.

This would essentially be an API endpoint that would return a JSON array of groups for a given UID. The easiest way to manage authentication would be IP whitelisting, as there are only two or three servers that would need to hit this API.

**Comment by RossIV** [comment]
This should be easily doable once Fractal is implemented. Hit the user.show endpoint and request inclusion of roles and teams relations.

**Comment by kberzinch** [comment]
Superseded by #334
