### ISSUE TITLE
Integrate Meilisearch into Nova

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#500]
Currently searching nova for a full name will return no results as all of the name columns are stored as parts. We did at one point have DB columns for full name but that has been moved to the PHP model and therefore isn't available for search in Nova.

**Comment by RossIV** [comment]
I don't know that I like this. The only field that _was_ in the database for names that got removed was the full name which was done with an in-database concat. I get your point about having the field accessible in Nova, but by having them separate in the DB we open the potential for lack of sync between different parts of a name.

**Comment by kberzinch** [comment]
What do you mean by lack of sync?

This doesn't have to be exposed to any other API, it just has to work for nova.

**Comment by kberzinch** [comment]
To clarify, I know the previous version was an in-database concat and I'm suggesting we do that again specifically to resolve this issue.

**Comment by RossIV** [comment]
The database concat was gross for a large number of reasons. One of the main ones is that, at least how we used it, it didn't support optional fields so if you only had first and last but no middle, you ended up with an extra space between them. We should look for _literally_ any other option before doing that again.

**Comment by JoshOldenburg** [comment]
Nova's search either searches DB columns or uses Laravel Scout: https://nova.laravel.com/docs/2.0/search/scout-integration.html. Since Scout comes with a driver for a paid service we could either look for another driver that would work or implement our own. Alternatively the in-DB concat with just the first_name+last_name fields would work for most people. Currently a little under 10% of users in production have a preferred name set that's not equal to their first name.

**Comment by kberzinch** [comment]
The issue is more that you can't search for full names at all, e.g. "kristaps berzinch" will return no results because there are no database columns with that value.

**Comment by kberzinch** [comment]
Maybe we should try this https://github.com/yabhq/laravel-scout-mysql-driver

**Comment by JoshOldenburg** [comment]
Here's another option for better search in Nova without that DB column: https://www.meilisearch.com/
