### ISSUE TITLE
Nova lens for nagging people about dues

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#508]
Show distinct inactive users who have attended a team in the last week

**Comment by kberzinch** [comment]
GTIDs without an associated user should also be captured in this list if possible. That may also just not be a thing depending on how we implement GTED stufs.

**Comment by JoshOldenburg** [comment]
Essentially a wrapper around this query:
`select distinct attendance.gtid, last_name, first_name from attendance left join users on users.gtid = attendance.gtid where attendance.created_at>"2018-10-01 00:00:00" and attendable_type="App\\Team" and attendable_id=2 and attendance.gtid not in (select distinct gtid from dues_transactions left join payments on dues_transactions.id = payments.payable_id left join dues_packages on dues_transactions.dues_package_id = dues_packages.id inner join users on dues_transactions.user_id = users.id where payments.id is not null and dues_transactions.id > 221 and payments.amount > 0);`
