### ISSUE TITLE
Illuminate\Database\QueryException in POST /api/v1/faset

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#54]
## Error in Apiary

**Illuminate\Database\QueryException** in **POST /api/v1/faset**
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`apiary_prod`.`faset_responses`, CONSTRAINT `faset_responses_faset_survey_id_foreign` FOREIGN KEY (`faset_survey_id`) REFERENCES `faset_surveys` (`id`)) (SQL: insert into `faset_responses` (`faset_survey_id`, `response`, `faset_visit_id`, `updated_at`, `created_at`) values (1, tour, 1, 2017-07-01 20:01:07, 2017-07-01 20:01:07))

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5957fd4fc60ddc001892e790?event_id=5957ff830e7aac00189179c1&i=gh&m=ci)

## Stacktrace

    app/FasetVisit.php:27 - App\FasetVisit::addFasetResponse
    app/Http/Controllers/FasetVisitController.php:31 - App\Http\Controllers\FasetVisitController::visit

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5957fd4fc60ddc001892e790?event_id=5957ff830e7aac00189179c1&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by ryanstrat** [comment]
You need to manually add a Question with ID 1 to the surveys table. This will be fixed permanently when forms are dynamically generated.

**Comment by kberzinch** [comment]
Confirmed fixed in staging and prod. I created a new issue to capture seeding this table.
