### ISSUE TITLE
Handle username@gatech.edu logins more gracefully

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#547]
GT Login will actually allow using username@gatech.edu in the username field, which allows authentication and gets passed to the receiving application. Currently this is handled in Apiary by the same error page that handles missing CAS attributes, although in this case we can and should provide more helpful feedback.

I opened ticket 761566 with TSC to get this fixed on GT Login's side but I doubt it will be fixed.

**Comment by kberzinch** [comment]
IAM closed it as won't fix (called it.)

>Entered on 11/28/2018 at 10:15:02 EST (GMT-0500) by John Bryson:
>Kristaps et al,
>
>It is in fact sometimes okay, even required, to use blah@domain to log into 'federated' type applications at various universities, as we are part of a federation of schools called Incommon. This is a natural result of the fact that each school in the federation, might have a username called 'john' so the way you can tell john from GT from john at GSU is by adding a domain to it. So we can tell john@gatech.edu from john@gsu.edu. This is part of a naming standard called eduPerson, if you are curious and would like to learn more.
>
>That said, we try to hide complexity from users where we can. But you may run into applications that do demand the domain be added to your username (at GT the domain is @gatech.edu).  
>
>It is up to each application to guide users on what is appropriate.  
>
>I will forward your observation, that about it not being clear, to the admins responsible for those systems.

**Comment by kberzinch** [comment]
obtw this issue was forwarded to cybersecurity vulnerability reporting due to a related security issue.

**Comment by JoshOldenburg** [comment]
Currently the app responds with a 500 error and generic error page for this.

**Comment by JoshOldenburg** [comment]
Fixed in #909.
