### ISSUE TITLE
Delete recruiting

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#566]
Background uploader is fiddly and has demonstrably caused data loss already. Suggest removing.

**Comment by kberzinch** [comment]
@ryanstrat suggested making this toggleable

**Comment by evan10s** [comment]
Consider replacing this with Hubspot forms + importing a list of emails in Mailchimp

**Comment by kberzinch** [comment]
After discussion during grooming we have decided to remove recruiting from Apiary entirely pending discussion with Cameron.
