### ISSUE TITLE
BadMethodCallException in GET /nova-api/attendance

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#569]
## Error in Apiary

**BadMethodCallException** in **GET /nova-api/attendance**
Method Illuminate\Database\Query\Builder::getForeignKey does not exist.

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5c5e1f1c3d7b94001ab460b9?event_id=5c5e1f2f0035aa0412020000&i=gh&m=ci)

## Stacktrace

    app/Http/Middleware/CASAuthenticate.php:63 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5c5e1f1c3d7b94001ab460b9?event_id=5c5e1f2f0035aa0412020000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
This is an upstream issue with Nova (probably.) laravel/nova-issues#1388

**Comment by JoshOldenburg** [comment]
I haven't seen this in recent history, so it being fixed upstream is probably correct.

**Comment by kberzinch** [comment]
Actually, this was my fault, but either way it is fixed now.

https://github.com/laravel/nova-issues/issues/1388#issuecomment-468969124
