### ISSUE TITLE
"Make a wish" button

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#57]
Add a button somewhere reasonably prominent where people can quickly and easily submit feedback. This is how Cisco products collect feedback and I think it's awesome and we should do it. I don't entirely know where that feedback should _go_ exactly though.

**Comment by ryanstrat** [comment]
I would just link this to a google form using a pre-filled form field with the URL of the page that the user was on when they clicked the link.

I don't want to focus on this right away, but once we build the global footer that will be on all standard pages, I have no issue dropping this there.

**Comment by kberzinch** [comment]
Google Form is here:  https://docs.google.com/forms/d/e/1FAIpQLSelERsYq3gLmHbWvVCWha5iCU8z3r9VYC0hCN4ArLpMAiysaQ/viewform?entry.1338203640=https://my.robojackets.org/faset
