### ISSUE TITLE
Nova polish

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#570]
## Attendance
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

## Payments
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

## Dues Packages
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

## Dues Transactions
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

## Events
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

## Recruiting Visits
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

## Teams
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

## Users
- [ ] All fields have obvious names or help text
- [ ] All fields have the most specific type available
- [ ] All fields have the correct visibility on index
- [ ] All fields have the correct visibility on view
- [ ] All fields have the correct visibility on create
- [ ] All fields have the correct visibility on edit
- [ ] Non-grouped fields at top of page

**Comment by JoshOldenburg** [comment]
I marked this as a good first issue because some individual parts of this are easy first issues. There's a ton here but any portion of this can stand alone in a pull request.

**Comment by evan10s** [comment]
Closing because too broad
