### ISSUE TITLE
Support contactless card reader at attendance kiosk

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#587]

**Comment by RossIV** [comment]
Use [this reader](https://www.amazon.com/ACS-ACR122U-Contactless-Smart-Reader/dp/B01KEGQFYY/) with [this code](https://github.com/RoboJackets/apiary-nfc-reader/) for contactless attendance.

To-Do:

- [ ] Resolve issues with reader code
- [ ] Add web socket support to kiosk page
- [ ] Add indicator of web socket status to kiosk page
- [ ] (RJ needs to) buy the reader
