### ISSUE TITLE
Write Privacy Policy

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#66]
Given the amount of personal information that this application stores on users, it is important to inform them of how we will and will not use it.

**Comment by kberzinch** [comment]
Not great but here's a start:
>RoboJackets may store the following information about you each time you log in, as reported by the Georgia Tech Enterprise Directory. You may opt out of this data collection by not using the application.
> - Your first name
> - Your last name
> - Your primary Georgia Tech email address
> - Your GTID number
> - Your Georgia Tech username
> - Your RoboJackets group assignnments in OrgSync
>
>RoboJackets may store the following information about you if you voluntarily provide it. You may opt out of this data collection by declining to provide it.
> - Your RoboJackets Slack user ID
> - Your personal email address
> - Your middle name
> - Your preferred name
> - Your phone number
> - Your emergency contact information, including their name and phone number
> - Your shirt and polo sizes
> - Your gender
> - Your ethnicity
>
>RoboJackets will only release information about you as strictly necessary to Georgia Tech campus departments or contractors performing work on our behalf, including but not limited to granting BuzzCard access to the shop, enrollment in SUMS, and reimbursement processing.
>
>Demographic information may be reported anonymized and in aggregate to current or potential sponsors.
>
>All other information will be kept in strict confidence and released only to RoboJackets officers in the course of conducting business.
