### ISSUE TITLE
Attendance export doesn't work on large datasets

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#688]
It seems to cap at around a 3-4KB CSV, ~200 attendance records

**Comment by kberzinch** [comment]
What happens above that size?

**Comment by JoshOldenburg** [comment]
The total number of attendance data points in the CSV file is not the same as the number of rows selected in Nova when the action was run.

**Comment by kberzinch** [comment]
It sounds like it's being truncated somewhere then
