### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError in GET /nova-api/users

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#708]
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /nova-api/users**
Return value of App\Nova\Filters\UserActive::apply() must be an instance of Illuminate\Database\Eloquent\Builder, instance of Chelout\RelationshipEvents\BelongsToMany returned

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5d190d1e2735a1001a4c7c24?event_id=5d190d1e0045f1bab1950000&i=gh&m=ci)

## Stacktrace

    Nova/Filters/UserActive.php:33 - App\Nova\Filters\UserActive::apply
    Http/Middleware/CASAuthenticate.php:59 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5d190d1e2735a1001a4c7c24?event_id=5d190d1e0045f1bab1950000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by JoshOldenburg** [comment]
I can't replicate this anymore, so I'm going to close this.

**Comment by kberzinch** [comment]
found it

**Comment by JoshOldenburg** [comment]
Replicate by filtering users by active on team detail
