### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by ryanstrat** [RoboJackets/apiary#74]
Add Google Analytics Support.

Account key should go in the environment file

**Comment by kberzinch** [comment]
I'm going to use the modern setup listed in [the documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/).
>The alternative async tracking snippet below adds support for preloading, which will provide a small performance boost on modern browsers, but can degrade to synchronous loading and execution on IE 9 and older mobile browsers that do not recognize the async script attribute. Only use this tracking snippet if your visitors primarily use modern browsers to access your site.

**Comment by kberzinch** [comment]
Prod environment has been configured.
