### ISSUE TITLE
Remove/add option to disable orgsync team sync

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#747]
Essentially revert #496 (or add option to disable it) since it is unnecessary now that Jedi is implemented and the groups went away with the transition to campus labs.

**Comment by kberzinch** [comment]
It looks like the entitlements are still in GTED, not sure if that's just left over.

**Comment by kberzinch** [comment]
Update, looks like those are left over, so we're good to remove that functionality.
