### ISSUE TITLE
Automatically ignore service accounts in PushToJedi job

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#787]

**Comment by kberzinch** [comment]
A service account shouldn't be sent to sync in normal code flows so idk about this. If this is something you're running into with tinker I would recommend filtering it there before you dispatch jobs.

**Comment by JoshOldenburg** [comment]
I ran into this by selecting all users in Nova and running the sync access action.

**Comment by kberzinch** [comment]
Mmm then it should probably be filtered in the nova action

**Comment by JoshOldenburg** [comment]
Probably technically dependent on #222
