### ISSUE TITLE
Add job to create users where necessary

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#815]
We can now search GTED by a GTID, so users should be created for attendance records without one. The architecture of this is TBD. It may also be useful to attach users to recruiting visits.

**Comment by JoshOldenburg** [comment]
Use this client library: https://github.gatech.edu/OIT-NetworkServices/BuzzAPIClient

**Comment by kberzinch** [comment]
That library needs some work before I would be comfortable adding it as a dependency.

**Comment by JoshOldenburg** [comment]
We should consider having a flag for whether a user has ever logged in with CAS.
