### ISSUE TITLE
Send last seen attendance swipe to JEDI

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#824]
This may be used for SUMS lockout in a future release of JEDI, pending management approval and developer bandwidth.

**Comment by JoshOldenburg** [comment]
Feedback from core:
- Send an email when it happens that includes an exit survey
- 4 week timeout
- Don't send emails over the summer

I'd suggest a job that runs daily (weekly?) that sends users (maybe active users only) who haven't attended anything with the kiosk in the time period to Jedi.
