### ISSUE TITLE
Resume book generation

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#825]
Upload resume on user profile semesterly, then generate one big PDF for companies

**Comment by kberzinch** [comment]
Single PDF is probably wonky to deal with on the receiving end. A ZIP file would be more useful.

**Comment by kberzinch** [comment]
For detecting images https://stackoverflow.com/a/32988533

**Comment by JoshOldenburg** [comment]
Per @ryanstrat in Slack, this should export one PDF for a given search criteria (major and graduation semester). Ensure the resumes are one page each and ideally verify they're black and white and have no images.
