### ISSUE TITLE
Add basic login checks from auth plugins

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#827]
Check for domain, require duo, network check?

Consider reusing error pages package

**Comment by kberzinch** [comment]
https://packages.robojackets.org/ has pre-built packages that provide a convenient way to determine a client's originating network and consistent error pages for problems with their GT Login session. Anything there should be accessible from the campus network; if you would like access to the GitHub repositories where those packages live, please ask in #it-helpdesk.

**Comment by JoshOldenburg** [comment]
This should have a check for missing GTID (guest accounts) too.
