### ISSUE TITLE
Illuminate\Database\QueryException in GET /nova-api/dues-transactions

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#885]
## Error in Apiary

**Illuminate\Database\QueryException** in **GET /nova-api/dues-transactions**
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous (SQL: select * from `dues_transactions` inner join `team_user` on `dues_transactions`.`user_id` = `team_user`.`user_id` where `team_user`.`team_id` = 1 and `dues_transactions`.`deleted_at` is null order by `id` asc limit 26 offset 0)

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5d9e77ca63991e00195755f4?event_id=5d9e77ca0050d015d63c0000&i=gh&m=ci)

## Stacktrace

    Http/Middleware/CASAuthenticate.php:59 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5d9e77ca63991e00195755f4?event_id=5d9e77ca0050d015d63c0000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
Maybe disable sorting by ID

**Comment by kberzinch** [comment]
marked GFI because sortable fields are easy to change, iirc

**Comment by georgeburdell** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Illuminate\Database\QueryException** in **PUT /nova-api/events/8**](https://app.bugsnag.com/robojackets/apiary/errors/5d9e77ca63991e00195755f4?event_id=5d9f7af70050df0b70c40000&i=gh&m=fx)
