### ISSUE TITLE
Attendance report week inconsistencies and phrasing

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#886]
The attendance report endpoint should use weeks starting on Sunday, not Monday (`%X $V` instead of `%x %v`), shouldn't include the current day, and should shift back to include one more previous day.

Additionally, the GUI for the attendance report should clarify what "average total people per week" means. It should also include a one week option.

**Comment by kberzinch** [comment]
Analytics moved to Metabase
