### ISSUE TITLE
Easier interface searching for and running export actions for multiple users

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#898]
Per discussion with Jonathan, this is useful for the core contact sheet, trips, and probably some other cases. I’m not sure what the interface for this would be.

**Comment by kberzinch** [comment]
IMHO for core contact sheet, use the team. For anything else use trips. See also #333, #341

**Comment by kberzinch** [comment]
Our current pattern is largely around building exports for specific business cases and I think we should maintain that.
