### ISSUE TITLE
Migrate all usernames to lowercase

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#953]
The uid CAS attribute is the lowercase version of the CAS username but strtolower is likely the exact same result.

**Comment by kberzinch** [comment]
`strtolower` is in fact the same result. The only other thing you might get in the CAS username field is @gatech.edu but you wouldn't get the `uid` field in that case.

**Comment by kberzinch** [comment]
There are no users currently in the database with a capital letter in their username and it appears CASv6 is normalizing the username input to lowercase on that end.
